services:
  voicegpt-backend:
    build: .
    container_name: voicegpt
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_PORT=${BACKEND_PORT}
    env_file:
      - .env
